language: python
python:
- '3.7'
services:
- postgresql
before_install:
- pip install codecov
install:
- pip install -r requirements.txt
deploy:
  provider: heroku
  api_key:
    secure: gibU6sL81ZVT8FIC3o/KRpv+aKHDFnblNyC3SNFszyMRP+eYcvNQUitRq9IeyrQTxtzeZWRQOUlBtY13eNIaC8Qw86fLJT55ok/ZpPGy14H0fKRkz66L+Nce6tGV+pIN/9X9FaKKiEzdTnq88f09ijT05lCo7Km/EE/50KJ7YyPElDGV8DuVvk9zG5f1d8Jy01XKtI6M/poCEDN9l5YtacAg7KwG8xiG6j1KgFDJ/PRgyBdGVy/HGLY1h/Kywc2UU1ztHHMfcFoYjButzna4LkV4c7zkEvU/9bBNaJ/0ykVdYh5qFRbXQLpqvsniYoUWQ+5JrI8fOEHrcXiyDZ5Co34mhxd7x71ndJutAmJcZYeA+iTj75U53pod4um4NTbLi9NyycidRUuOBGFgxANnoYMbYMVKXGkUfkGkA8LfHZUdmmYMrq+K2YGwUyIlRrW9r5M+iUGL0hc7KXsms+vMzPWp2KTjT77/NVk8ebiF5A89dzqwOkO7j5ZIdcQxRB7+h4UmdC8OGMo/l40+fxt+jYgXAofzW/USUsUnd6tPTv4vdcGu+tYuNzD5bewmGkmlgHysLUho4QfRYR2OlxN5KcPDDb1iBcqCa4WqGh1+yqui4mIq6aWWKceBFCBSJ7GcmPOp74By0bbQty4/qticYwxgC8fIJZY7igeMGmiw3fw=
  app: gt-unicore
  on:
    branch: main
before_script:
- psql -c 'CREATE DATABASE gt_tests WITH ENCODING = "UTF8";' -U postgres
script:
- coverage run -m unittest tests/rates_tests.py
- flake8 --ignore E501,F405,F403,E711,R504,D102,D202,D208 --filename=app/core/rates,
  app/core/models.py
after_success:
- codecov
