language: python
python:
- '3.7'
services:
- postgresql
before_install:
- pip install codecov
install:
- pip install -r requirements.txt
deploy:
  provider: heroku
  api_key:
    secure: E0ElDoDP8YMEZ/EJtWrcjKwQo89Tnmc/afh2T1VDNanJ+uKl0bXe6AOFhCGyMq7Vwt47acvqGXIMd0Jn1vt3+vgo4htSXm9TjsaXLI2s/wJwxvOxDMiLMm1BUt74VTkMA/b98ZNk27zE5H3UA1JCBoRufQ+AVZ5gn/8Eszx7bowIQIj1/dVOpii/TumtWhZt6rms0GF5UHwIwm7QIVe4r8xeb9/m2DJHPTKPndzfujyNb2mERqGs3o2LgoHXBeS5k2wyDR73T1z6Qkr2i3su2izAhFnuskhY2TZcQUeQJaPqSJREk7MGiGKV98TPDfVT+r3STkRu4vxafNanEpJlQ9WrYrC9T/2vV9bM0U3XFI3/fm/gyJmBvswCKbvjlDluKoPfZcbhvJDfCXOMaU4hCgE1PjY+cPiw73vu2lM9yPLluzLRckAix/oCumaISPvVprrKvpjnuwbJEBjX5bLvGSRiiqbtBY5qfQMQOzk1i+AVEk03Mk+0asGY17mY+6OF3OsSu4yNw0CHnHmJJu76qQIYWUXpQ67mEBlTMz6p9HU+NibKOTAV4e46YN/DzfLcT5J/MWyjxv1lydUE0F4SlubwfQ5ivk1hKHgPfXSDHJ6bfNKFtHHZeAsnOJKJJA9UmoelkdGhqvHO/xgfzkCHCOdNHKqwYz+3wC2kUPQEcE8=
  app: gt-unicore
  on:
    branch: main
before_script:
- psql -c 'CREATE DATABASE gt_tests WITH ENCODING = "UTF8";' -U postgres
script:
- coverage run -m unittest tests/rates_tests.py
- flake8 --ignore E501,F405,F403,E711,R504,D102,D202,D208 --filename=app/core/rates,
  app/core/models.py
after_success:
- codecov
